services:
  currency-converter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GCP_PROJECT_ID=joy-currency-conversion
      - DB_NAME=currency_conversion
      - CLOUD_SQL_CONNECTION_NAME=joy-currency-conversion:us-central1:currency-conversion-db
    volumes:
      - /cloudsql:/cloudsql
